replicaCount: 2
image:
  repository: 142166253229.dkr.ecr.ap-south-1.amazonaws.com/backend
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000

env:
  flaskEnv: "production"
  # DATABASE_URL should be provided via a secret
  databaseSecretName: "backend-secret"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
