replicaCount: 2
image:
  repository: 142166253229.dkr.ecr.ap-south-1.amazonaws.com/deployment/frontend-app
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
